name: quran
description: A comprehensive, lightweight, and offline-first Quran data package for Dart and Flutter applications.
version: 1.1.0
homepage: https://github.com/Muslims-Community/quran-data-dart
repository: https://github.com/Muslims-Community/quran-data-dart

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.0

flutter:
  assets:
    - assets/quran.json

# Dart package configuration
publish_to: 'https://pub.dev'

topics:
  - quran
  - islam
  - arabic
  - islamic
  - religious
  - offline
  - flutter
  - dart

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

funding:
  - https://github.com/sponsors/Muslims-Community